// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EditInstruction.proto

package com.google.errorprone.bugpatterns.T2R.common.Models;

public final class EditInstructionOuterClass {
  private EditInstructionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Models.EditCmd}
   */
  public enum EditCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Random = 0;</code>
     */
    Random(0),
    /**
     * <code>DoNotMigrate = 1;</code>
     */
    DoNotMigrate(1),
    /**
     * <code>Identity = 2;</code>
     */
    Identity(2),
    /**
     * <code>Remove = 4;</code>
     */
    Remove(4),
    /**
     * <code>Chain = 5;</code>
     */
    Chain(5),
    ;

    /**
     * <code>Random = 0;</code>
     */
    public static final int Random_VALUE = 0;
    /**
     * <code>DoNotMigrate = 1;</code>
     */
    public static final int DoNotMigrate_VALUE = 1;
    /**
     * <code>Identity = 2;</code>
     */
    public static final int Identity_VALUE = 2;
    /**
     * <code>Remove = 4;</code>
     */
    public static final int Remove_VALUE = 4;
    /**
     * <code>Chain = 5;</code>
     */
    public static final int Chain_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EditCmd valueOf(int value) {
      return forNumber(value);
    }

    public static EditCmd forNumber(int value) {
      switch (value) {
        case 0: return Random;
        case 1: return DoNotMigrate;
        case 2: return Identity;
        case 4: return Remove;
        case 5: return Chain;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EditCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EditCmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EditCmd>() {
            public EditCmd findValueByNumber(int number) {
              return EditCmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final EditCmd[] VALUES = values();

    public static EditCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EditCmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Models.EditCmd)
  }

  public interface EditInstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.EditInstruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Models.EditCmd cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>optional .Models.EditCmd cmd = 1;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd getCmd();

    /**
     * <code>optional string editName = 2;</code>
     */
    boolean hasEditName();
    /**
     * <code>optional string editName = 2;</code>
     */
    java.lang.String getEditName();
    /**
     * <code>optional string editName = 2;</code>
     */
    com.google.protobuf.ByteString
        getEditNameBytes();

    /**
     * <code>optional .Models.TypeInfo editType = 3;</code>
     */
    boolean hasEditType();
    /**
     * <code>optional .Models.TypeInfo editType = 3;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo getEditType();
    /**
     * <code>optional .Models.TypeInfo editType = 3;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfoOrBuilder getEditTypeOrBuilder();

    public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.EditInstrCase getEditInstrCase();
  }
  /**
   * Protobuf type {@code Models.EditInstruction}
   */
  public  static final class EditInstruction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.EditInstruction)
      EditInstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EditInstruction.newBuilder() to construct.
    private EditInstruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EditInstruction() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EditInstruction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd value = com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                editInstrCase_ = 1;
                editInstr_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              editInstrCase_ = 2;
              editInstr_ = bs;
              break;
            }
            case 26: {
              com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.Builder subBuilder = null;
              if (editInstrCase_ == 3) {
                subBuilder = ((com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_).toBuilder();
              }
              editInstr_ =
                  input.readMessage(com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_);
                editInstr_ = subBuilder.buildPartial();
              }
              editInstrCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.internal_static_Models_EditInstruction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.internal_static_Models_EditInstruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.class, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder.class);
    }

    private int bitField0_;
    private int editInstrCase_ = 0;
    private java.lang.Object editInstr_;
    public enum EditInstrCase
        implements com.google.protobuf.Internal.EnumLite {
      CMD(1),
      EDITNAME(2),
      EDITTYPE(3),
      EDITINSTR_NOT_SET(0);
      private final int value;
      private EditInstrCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EditInstrCase valueOf(int value) {
        return forNumber(value);
      }

      public static EditInstrCase forNumber(int value) {
        switch (value) {
          case 1: return CMD;
          case 2: return EDITNAME;
          case 3: return EDITTYPE;
          case 0: return EDITINSTR_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EditInstrCase
    getEditInstrCase() {
      return EditInstrCase.forNumber(
          editInstrCase_);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    /**
     * <code>optional .Models.EditCmd cmd = 1;</code>
     */
    public boolean hasCmd() {
      return editInstrCase_ == 1;
    }
    /**
     * <code>optional .Models.EditCmd cmd = 1;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd getCmd() {
      if (editInstrCase_ == 1) {
        com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd result = com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd.valueOf(
            (java.lang.Integer) editInstr_);
        return result == null ? com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd.Random : result;
      }
      return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd.Random;
    }

    public static final int EDITNAME_FIELD_NUMBER = 2;
    /**
     * <code>optional string editName = 2;</code>
     */
    public boolean hasEditName() {
      return editInstrCase_ == 2;
    }
    /**
     * <code>optional string editName = 2;</code>
     */
    public java.lang.String getEditName() {
      java.lang.Object ref = "";
      if (editInstrCase_ == 2) {
        ref = editInstr_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (editInstrCase_ == 2)) {
          editInstr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string editName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEditNameBytes() {
      java.lang.Object ref = "";
      if (editInstrCase_ == 2) {
        ref = editInstr_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (editInstrCase_ == 2) {
          editInstr_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EDITTYPE_FIELD_NUMBER = 3;
    /**
     * <code>optional .Models.TypeInfo editType = 3;</code>
     */
    public boolean hasEditType() {
      return editInstrCase_ == 3;
    }
    /**
     * <code>optional .Models.TypeInfo editType = 3;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo getEditType() {
      if (editInstrCase_ == 3) {
         return (com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_;
      }
      return com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.getDefaultInstance();
    }
    /**
     * <code>optional .Models.TypeInfo editType = 3;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfoOrBuilder getEditTypeOrBuilder() {
      if (editInstrCase_ == 3) {
         return (com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_;
      }
      return com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (editInstrCase_ == 1) {
        output.writeEnum(1, ((java.lang.Integer) editInstr_));
      }
      if (editInstrCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, editInstr_);
      }
      if (editInstrCase_ == 3) {
        output.writeMessage(3, (com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (editInstrCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ((java.lang.Integer) editInstr_));
      }
      if (editInstrCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, editInstr_);
      }
      if (editInstrCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction)) {
        return super.equals(obj);
      }
      com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction other = (com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction) obj;

      boolean result = true;
      result = result && getEditInstrCase().equals(
          other.getEditInstrCase());
      if (!result) return false;
      switch (editInstrCase_) {
        case 1:
          result = result && getCmd()
              .equals(other.getCmd());
          break;
        case 2:
          result = result && getEditName()
              .equals(other.getEditName());
          break;
        case 3:
          result = result && getEditType()
              .equals(other.getEditType());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (editInstrCase_) {
        case 1:
          hash = (37 * hash) + CMD_FIELD_NUMBER;
          hash = (53 * hash) + getCmd().getNumber();
          break;
        case 2:
          hash = (37 * hash) + EDITNAME_FIELD_NUMBER;
          hash = (53 * hash) + getEditName().hashCode();
          break;
        case 3:
          hash = (37 * hash) + EDITTYPE_FIELD_NUMBER;
          hash = (53 * hash) + getEditType().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.EditInstruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.EditInstruction)
        com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.internal_static_Models_EditInstruction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.internal_static_Models_EditInstruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.class, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder.class);
      }

      // Construct using com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        editInstrCase_ = 0;
        editInstr_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.internal_static_Models_EditInstruction_descriptor;
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction getDefaultInstanceForType() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.getDefaultInstance();
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction build() {
        com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction buildPartial() {
        com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction result = new com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (editInstrCase_ == 1) {
          result.editInstr_ = editInstr_;
        }
        if (editInstrCase_ == 2) {
          result.editInstr_ = editInstr_;
        }
        if (editInstrCase_ == 3) {
          if (editTypeBuilder_ == null) {
            result.editInstr_ = editInstr_;
          } else {
            result.editInstr_ = editTypeBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.editInstrCase_ = editInstrCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction) {
          return mergeFrom((com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction other) {
        if (other == com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.getDefaultInstance()) return this;
        switch (other.getEditInstrCase()) {
          case CMD: {
            setCmd(other.getCmd());
            break;
          }
          case EDITNAME: {
            editInstrCase_ = 2;
            editInstr_ = other.editInstr_;
            onChanged();
            break;
          }
          case EDITTYPE: {
            mergeEditType(other.getEditType());
            break;
          }
          case EDITINSTR_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int editInstrCase_ = 0;
      private java.lang.Object editInstr_;
      public EditInstrCase
          getEditInstrCase() {
        return EditInstrCase.forNumber(
            editInstrCase_);
      }

      public Builder clearEditInstr() {
        editInstrCase_ = 0;
        editInstr_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>optional .Models.EditCmd cmd = 1;</code>
       */
      public boolean hasCmd() {
        return editInstrCase_ == 1;
      }
      /**
       * <code>optional .Models.EditCmd cmd = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd getCmd() {
        if (editInstrCase_ == 1) {
          com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd result = com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd.valueOf(
              (java.lang.Integer) editInstr_);
          return result == null ? com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd.Random : result;
        }
        return com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd.Random;
      }
      /**
       * <code>optional .Models.EditCmd cmd = 1;</code>
       */
      public Builder setCmd(com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditCmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        editInstrCase_ = 1;
        editInstr_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Models.EditCmd cmd = 1;</code>
       */
      public Builder clearCmd() {
        if (editInstrCase_ == 1) {
          editInstrCase_ = 0;
          editInstr_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional string editName = 2;</code>
       */
      public boolean hasEditName() {
        return editInstrCase_ == 2;
      }
      /**
       * <code>optional string editName = 2;</code>
       */
      public java.lang.String getEditName() {
        java.lang.Object ref = "";
        if (editInstrCase_ == 2) {
          ref = editInstr_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (editInstrCase_ == 2) {
            if (bs.isValidUtf8()) {
              editInstr_ = s;
            }
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string editName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEditNameBytes() {
        java.lang.Object ref = "";
        if (editInstrCase_ == 2) {
          ref = editInstr_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (editInstrCase_ == 2) {
            editInstr_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string editName = 2;</code>
       */
      public Builder setEditName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  editInstrCase_ = 2;
        editInstr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string editName = 2;</code>
       */
      public Builder clearEditName() {
        if (editInstrCase_ == 2) {
          editInstrCase_ = 0;
          editInstr_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string editName = 2;</code>
       */
      public Builder setEditNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  editInstrCase_ = 2;
        editInstr_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo, com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfoOrBuilder> editTypeBuilder_;
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public boolean hasEditType() {
        return editInstrCase_ == 3;
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo getEditType() {
        if (editTypeBuilder_ == null) {
          if (editInstrCase_ == 3) {
            return (com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_;
          }
          return com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.getDefaultInstance();
        } else {
          if (editInstrCase_ == 3) {
            return editTypeBuilder_.getMessage();
          }
          return com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public Builder setEditType(com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo value) {
        if (editTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          editInstr_ = value;
          onChanged();
        } else {
          editTypeBuilder_.setMessage(value);
        }
        editInstrCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public Builder setEditType(
          com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.Builder builderForValue) {
        if (editTypeBuilder_ == null) {
          editInstr_ = builderForValue.build();
          onChanged();
        } else {
          editTypeBuilder_.setMessage(builderForValue.build());
        }
        editInstrCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public Builder mergeEditType(com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo value) {
        if (editTypeBuilder_ == null) {
          if (editInstrCase_ == 3 &&
              editInstr_ != com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.getDefaultInstance()) {
            editInstr_ = com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.newBuilder((com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_)
                .mergeFrom(value).buildPartial();
          } else {
            editInstr_ = value;
          }
          onChanged();
        } else {
          if (editInstrCase_ == 3) {
            editTypeBuilder_.mergeFrom(value);
          }
          editTypeBuilder_.setMessage(value);
        }
        editInstrCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public Builder clearEditType() {
        if (editTypeBuilder_ == null) {
          if (editInstrCase_ == 3) {
            editInstrCase_ = 0;
            editInstr_ = null;
            onChanged();
          }
        } else {
          if (editInstrCase_ == 3) {
            editInstrCase_ = 0;
            editInstr_ = null;
          }
          editTypeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.Builder getEditTypeBuilder() {
        return getEditTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfoOrBuilder getEditTypeOrBuilder() {
        if ((editInstrCase_ == 3) && (editTypeBuilder_ != null)) {
          return editTypeBuilder_.getMessageOrBuilder();
        } else {
          if (editInstrCase_ == 3) {
            return (com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_;
          }
          return com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Models.TypeInfo editType = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo, com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfoOrBuilder> 
          getEditTypeFieldBuilder() {
        if (editTypeBuilder_ == null) {
          if (!(editInstrCase_ == 3)) {
            editInstr_ = com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.getDefaultInstance();
          }
          editTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo, com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfoOrBuilder>(
                  (com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.TypeInfo) editInstr_,
                  getParentForChildren(),
                  isClean());
          editInstr_ = null;
        }
        editInstrCase_ = 3;
        onChanged();;
        return editTypeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.EditInstruction)
    }

    // @@protoc_insertion_point(class_scope:Models.EditInstruction)
    private static final com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction();
    }

    public static com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EditInstruction>
        PARSER = new com.google.protobuf.AbstractParser<EditInstruction>() {
      public EditInstruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EditInstruction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EditInstruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EditInstruction> getParserForType() {
      return PARSER;
    }

    public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_EditInstruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_EditInstruction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EditInstruction.proto\022\006Models\032\023TypeSig" +
      "nature.proto\"x\n\017EditInstruction\022\036\n\003cmd\030\001" +
      " \001(\0162\017.Models.EditCmdH\000\022\022\n\010editName\030\002 \001(" +
      "\tH\000\022$\n\010editType\030\003 \001(\0132\020.Models.TypeInfoH" +
      "\000B\013\n\teditInstr*L\n\007EditCmd\022\n\n\006Random\020\000\022\020\n" +
      "\014DoNotMigrate\020\001\022\014\n\010Identity\020\002\022\n\n\006Remove\020" +
      "\004\022\t\n\005Chain\020\005B5\n3com.google.errorprone.bu" +
      "gpatterns.T2R.common.Models"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Models_EditInstruction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_EditInstruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_EditInstruction_descriptor,
        new java.lang.String[] { "Cmd", "EditName", "EditType", "EditInstr", });
    com.google.errorprone.bugpatterns.T2R.common.Models.TypeSignatureOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
