// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Refactorable.proto

package com.google.errorprone.bugpatterns.T2R.common.Models;

public final class RefactorableOuterClass {
  private RefactorableOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RefactorableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.Refactorable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Models.Identification id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional .Models.Identification id = 1;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification getId();
    /**
     * <code>optional .Models.Identification id = 1;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.IdentificationOrBuilder getIdOrBuilder();

    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction> 
        getEditInstructionsList();
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction getEditInstructions(int index);
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    int getEditInstructionsCount();
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder> 
        getEditInstructionsOrBuilderList();
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder getEditInstructionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Models.Refactorable}
   */
  public  static final class Refactorable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.Refactorable)
      RefactorableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Refactorable.newBuilder() to construct.
    private Refactorable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Refactorable() {
      editInstructions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Refactorable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                editInstructions_ = new java.util.ArrayList<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction>();
                mutable_bitField0_ |= 0x00000002;
              }
              editInstructions_.add(
                  input.readMessage(com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          editInstructions_ = java.util.Collections.unmodifiableList(editInstructions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.internal_static_Models_Refactorable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.internal_static_Models_Refactorable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.class, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification id_;
    /**
     * <code>optional .Models.Identification id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Models.Identification id = 1;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification getId() {
      return id_ == null ? com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.getDefaultInstance() : id_;
    }
    /**
     * <code>optional .Models.Identification id = 1;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.IdentificationOrBuilder getIdOrBuilder() {
      return id_ == null ? com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.getDefaultInstance() : id_;
    }

    public static final int EDITINSTRUCTIONS_FIELD_NUMBER = 2;
    private java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction> editInstructions_;
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction> getEditInstructionsList() {
      return editInstructions_;
    }
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    public java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder> 
        getEditInstructionsOrBuilderList() {
      return editInstructions_;
    }
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    public int getEditInstructionsCount() {
      return editInstructions_.size();
    }
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction getEditInstructions(int index) {
      return editInstructions_.get(index);
    }
    /**
     * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder getEditInstructionsOrBuilder(
        int index) {
      return editInstructions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasId()) {
        if (!getId().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getId());
      }
      for (int i = 0; i < editInstructions_.size(); i++) {
        output.writeMessage(2, editInstructions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      for (int i = 0; i < editInstructions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, editInstructions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable)) {
        return super.equals(obj);
      }
      com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable other = (com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && getEditInstructionsList()
          .equals(other.getEditInstructionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (getEditInstructionsCount() > 0) {
        hash = (37 * hash) + EDITINSTRUCTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getEditInstructionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.Refactorable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.Refactorable)
        com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.internal_static_Models_Refactorable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.internal_static_Models_Refactorable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.class, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder.class);
      }

      // Construct using com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdFieldBuilder();
          getEditInstructionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (editInstructionsBuilder_ == null) {
          editInstructions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          editInstructionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.internal_static_Models_Refactorable_descriptor;
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable getDefaultInstanceForType() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.getDefaultInstance();
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable build() {
        com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable buildPartial() {
        com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable result = new com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        if (editInstructionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            editInstructions_ = java.util.Collections.unmodifiableList(editInstructions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.editInstructions_ = editInstructions_;
        } else {
          result.editInstructions_ = editInstructionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable) {
          return mergeFrom((com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable other) {
        if (other == com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (editInstructionsBuilder_ == null) {
          if (!other.editInstructions_.isEmpty()) {
            if (editInstructions_.isEmpty()) {
              editInstructions_ = other.editInstructions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEditInstructionsIsMutable();
              editInstructions_.addAll(other.editInstructions_);
            }
            onChanged();
          }
        } else {
          if (!other.editInstructions_.isEmpty()) {
            if (editInstructionsBuilder_.isEmpty()) {
              editInstructionsBuilder_.dispose();
              editInstructionsBuilder_ = null;
              editInstructions_ = other.editInstructions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              editInstructionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEditInstructionsFieldBuilder() : null;
            } else {
              editInstructionsBuilder_.addAllMessages(other.editInstructions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasId()) {
          if (!getId().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification, com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.IdentificationOrBuilder> idBuilder_;
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification getId() {
        if (idBuilder_ == null) {
          return id_ == null ? com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public Builder setId(com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public Builder setId(
          com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public Builder mergeId(com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              id_ != null &&
              id_ != com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.getDefaultInstance()) {
            id_ =
              com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.IdentificationOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>optional .Models.Identification id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification, com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.IdentificationOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification, com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.Identification.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.IdentificationOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction> editInstructions_ =
        java.util.Collections.emptyList();
      private void ensureEditInstructionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          editInstructions_ = new java.util.ArrayList<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction>(editInstructions_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder> editInstructionsBuilder_;

      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction> getEditInstructionsList() {
        if (editInstructionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(editInstructions_);
        } else {
          return editInstructionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public int getEditInstructionsCount() {
        if (editInstructionsBuilder_ == null) {
          return editInstructions_.size();
        } else {
          return editInstructionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction getEditInstructions(int index) {
        if (editInstructionsBuilder_ == null) {
          return editInstructions_.get(index);
        } else {
          return editInstructionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder setEditInstructions(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction value) {
        if (editInstructionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEditInstructionsIsMutable();
          editInstructions_.set(index, value);
          onChanged();
        } else {
          editInstructionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder setEditInstructions(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder builderForValue) {
        if (editInstructionsBuilder_ == null) {
          ensureEditInstructionsIsMutable();
          editInstructions_.set(index, builderForValue.build());
          onChanged();
        } else {
          editInstructionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder addEditInstructions(com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction value) {
        if (editInstructionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEditInstructionsIsMutable();
          editInstructions_.add(value);
          onChanged();
        } else {
          editInstructionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder addEditInstructions(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction value) {
        if (editInstructionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEditInstructionsIsMutable();
          editInstructions_.add(index, value);
          onChanged();
        } else {
          editInstructionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder addEditInstructions(
          com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder builderForValue) {
        if (editInstructionsBuilder_ == null) {
          ensureEditInstructionsIsMutable();
          editInstructions_.add(builderForValue.build());
          onChanged();
        } else {
          editInstructionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder addEditInstructions(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder builderForValue) {
        if (editInstructionsBuilder_ == null) {
          ensureEditInstructionsIsMutable();
          editInstructions_.add(index, builderForValue.build());
          onChanged();
        } else {
          editInstructionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder addAllEditInstructions(
          java.lang.Iterable<? extends com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction> values) {
        if (editInstructionsBuilder_ == null) {
          ensureEditInstructionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, editInstructions_);
          onChanged();
        } else {
          editInstructionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder clearEditInstructions() {
        if (editInstructionsBuilder_ == null) {
          editInstructions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          editInstructionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public Builder removeEditInstructions(int index) {
        if (editInstructionsBuilder_ == null) {
          ensureEditInstructionsIsMutable();
          editInstructions_.remove(index);
          onChanged();
        } else {
          editInstructionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder getEditInstructionsBuilder(
          int index) {
        return getEditInstructionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder getEditInstructionsOrBuilder(
          int index) {
        if (editInstructionsBuilder_ == null) {
          return editInstructions_.get(index);  } else {
          return editInstructionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder> 
           getEditInstructionsOrBuilderList() {
        if (editInstructionsBuilder_ != null) {
          return editInstructionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(editInstructions_);
        }
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder addEditInstructionsBuilder() {
        return getEditInstructionsFieldBuilder().addBuilder(
            com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder addEditInstructionsBuilder(
          int index) {
        return getEditInstructionsFieldBuilder().addBuilder(
            index, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.EditInstruction editInstructions = 2;</code>
       */
      public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder> 
           getEditInstructionsBuilderList() {
        return getEditInstructionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder> 
          getEditInstructionsFieldBuilder() {
        if (editInstructionsBuilder_ == null) {
          editInstructionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstruction.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.EditInstructionOrBuilder>(
                  editInstructions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          editInstructions_ = null;
        }
        return editInstructionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.Refactorable)
    }

    // @@protoc_insertion_point(class_scope:Models.Refactorable)
    private static final com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable();
    }

    public static com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Refactorable>
        PARSER = new com.google.protobuf.AbstractParser<Refactorable>() {
      public Refactorable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Refactorable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Refactorable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Refactorable> getParserForType() {
      return PARSER;
    }

    public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_Refactorable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_Refactorable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Refactorable.proto\022\006Models\032\024Identifica" +
      "tion.proto\032\025EditInstruction.proto\"e\n\014Ref" +
      "actorable\022\"\n\002id\030\001 \001(\0132\026.Models.Identific" +
      "ation\0221\n\020editInstructions\030\002 \003(\0132\027.Models" +
      ".EditInstructionB5\n3com.google.errorpron" +
      "e.bugpatterns.T2R.common.Models"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.getDescriptor(),
          com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Models_Refactorable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_Refactorable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_Refactorable_descriptor,
        new java.lang.String[] { "Id", "EditInstructions", });
    com.google.errorprone.bugpatterns.T2R.common.Models.IdentificationOuterClass.getDescriptor();
    com.google.errorprone.bugpatterns.T2R.common.Models.EditInstructionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
