// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TFGRefactorable.proto

package com.google.errorprone.bugpatterns.T2R.common.Models;

public final class TFGRefactorableOuterClass {
  private TFGRefactorableOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TFGRefactorableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.TFGRefactorable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable> 
        getNodesList();
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable getNodes(int index);
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder getNodesOrBuilder(
        int index);

    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge> 
        getEdgesList();
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge getEdges(int index);
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    int getEdgesCount();
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder> 
        getEdgesOrBuilderList();
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder getEdgesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Models.TFGRefactorable}
   */
  public  static final class TFGRefactorable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.TFGRefactorable)
      TFGRefactorableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TFGRefactorable.newBuilder() to construct.
    private TFGRefactorable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TFGRefactorable() {
      nodes_ = java.util.Collections.emptyList();
      edges_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TFGRefactorable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nodes_ = new java.util.ArrayList<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodes_.add(
                  input.readMessage(com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                edges_ = new java.util.ArrayList<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge>();
                mutable_bitField0_ |= 0x00000002;
              }
              edges_.add(
                  input.readMessage(com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          edges_ = java.util.Collections.unmodifiableList(edges_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.class, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.Builder.class);
    }

    public interface REdgeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Models.TFGRefactorable.REdge)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 fst = 1;</code>
       */
      boolean hasFst();
      /**
       * <code>required int32 fst = 1;</code>
       */
      int getFst();

      /**
       * <code>required int32 snd = 2;</code>
       */
      boolean hasSnd();
      /**
       * <code>required int32 snd = 2;</code>
       */
      int getSnd();

      /**
       * <code>optional string edgeValue = 3;</code>
       */
      boolean hasEdgeValue();
      /**
       * <code>optional string edgeValue = 3;</code>
       */
      java.lang.String getEdgeValue();
      /**
       * <code>optional string edgeValue = 3;</code>
       */
      com.google.protobuf.ByteString
          getEdgeValueBytes();
    }
    /**
     * Protobuf type {@code Models.TFGRefactorable.REdge}
     */
    public  static final class REdge extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Models.TFGRefactorable.REdge)
        REdgeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use REdge.newBuilder() to construct.
      private REdge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private REdge() {
        fst_ = 0;
        snd_ = 0;
        edgeValue_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private REdge(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                fst_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                snd_ = input.readInt32();
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                edgeValue_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_REdge_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_REdge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.class, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder.class);
      }

      private int bitField0_;
      public static final int FST_FIELD_NUMBER = 1;
      private int fst_;
      /**
       * <code>required int32 fst = 1;</code>
       */
      public boolean hasFst() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 fst = 1;</code>
       */
      public int getFst() {
        return fst_;
      }

      public static final int SND_FIELD_NUMBER = 2;
      private int snd_;
      /**
       * <code>required int32 snd = 2;</code>
       */
      public boolean hasSnd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 snd = 2;</code>
       */
      public int getSnd() {
        return snd_;
      }

      public static final int EDGEVALUE_FIELD_NUMBER = 3;
      private volatile java.lang.Object edgeValue_;
      /**
       * <code>optional string edgeValue = 3;</code>
       */
      public boolean hasEdgeValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string edgeValue = 3;</code>
       */
      public java.lang.String getEdgeValue() {
        java.lang.Object ref = edgeValue_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            edgeValue_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string edgeValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEdgeValueBytes() {
        java.lang.Object ref = edgeValue_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          edgeValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasFst()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSnd()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, fst_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, snd_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, edgeValue_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, fst_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, snd_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, edgeValue_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge)) {
          return super.equals(obj);
        }
        com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge other = (com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge) obj;

        boolean result = true;
        result = result && (hasFst() == other.hasFst());
        if (hasFst()) {
          result = result && (getFst()
              == other.getFst());
        }
        result = result && (hasSnd() == other.hasSnd());
        if (hasSnd()) {
          result = result && (getSnd()
              == other.getSnd());
        }
        result = result && (hasEdgeValue() == other.hasEdgeValue());
        if (hasEdgeValue()) {
          result = result && getEdgeValue()
              .equals(other.getEdgeValue());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasFst()) {
          hash = (37 * hash) + FST_FIELD_NUMBER;
          hash = (53 * hash) + getFst();
        }
        if (hasSnd()) {
          hash = (37 * hash) + SND_FIELD_NUMBER;
          hash = (53 * hash) + getSnd();
        }
        if (hasEdgeValue()) {
          hash = (37 * hash) + EDGEVALUE_FIELD_NUMBER;
          hash = (53 * hash) + getEdgeValue().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Models.TFGRefactorable.REdge}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Models.TFGRefactorable.REdge)
          com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_REdge_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_REdge_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.class, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder.class);
        }

        // Construct using com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          fst_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          snd_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          edgeValue_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_REdge_descriptor;
        }

        public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge getDefaultInstanceForType() {
          return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.getDefaultInstance();
        }

        public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge build() {
          com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge buildPartial() {
          com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge result = new com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.fst_ = fst_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.snd_ = snd_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.edgeValue_ = edgeValue_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge) {
            return mergeFrom((com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge other) {
          if (other == com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.getDefaultInstance()) return this;
          if (other.hasFst()) {
            setFst(other.getFst());
          }
          if (other.hasSnd()) {
            setSnd(other.getSnd());
          }
          if (other.hasEdgeValue()) {
            bitField0_ |= 0x00000004;
            edgeValue_ = other.edgeValue_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasFst()) {
            return false;
          }
          if (!hasSnd()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int fst_ ;
        /**
         * <code>required int32 fst = 1;</code>
         */
        public boolean hasFst() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 fst = 1;</code>
         */
        public int getFst() {
          return fst_;
        }
        /**
         * <code>required int32 fst = 1;</code>
         */
        public Builder setFst(int value) {
          bitField0_ |= 0x00000001;
          fst_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 fst = 1;</code>
         */
        public Builder clearFst() {
          bitField0_ = (bitField0_ & ~0x00000001);
          fst_ = 0;
          onChanged();
          return this;
        }

        private int snd_ ;
        /**
         * <code>required int32 snd = 2;</code>
         */
        public boolean hasSnd() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 snd = 2;</code>
         */
        public int getSnd() {
          return snd_;
        }
        /**
         * <code>required int32 snd = 2;</code>
         */
        public Builder setSnd(int value) {
          bitField0_ |= 0x00000002;
          snd_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 snd = 2;</code>
         */
        public Builder clearSnd() {
          bitField0_ = (bitField0_ & ~0x00000002);
          snd_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object edgeValue_ = "";
        /**
         * <code>optional string edgeValue = 3;</code>
         */
        public boolean hasEdgeValue() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string edgeValue = 3;</code>
         */
        public java.lang.String getEdgeValue() {
          java.lang.Object ref = edgeValue_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              edgeValue_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string edgeValue = 3;</code>
         */
        public com.google.protobuf.ByteString
            getEdgeValueBytes() {
          java.lang.Object ref = edgeValue_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            edgeValue_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string edgeValue = 3;</code>
         */
        public Builder setEdgeValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          edgeValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string edgeValue = 3;</code>
         */
        public Builder clearEdgeValue() {
          bitField0_ = (bitField0_ & ~0x00000004);
          edgeValue_ = getDefaultInstance().getEdgeValue();
          onChanged();
          return this;
        }
        /**
         * <code>optional string edgeValue = 3;</code>
         */
        public Builder setEdgeValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          edgeValue_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Models.TFGRefactorable.REdge)
      }

      // @@protoc_insertion_point(class_scope:Models.TFGRefactorable.REdge)
      private static final com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge();
      }

      public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<REdge>
          PARSER = new com.google.protobuf.AbstractParser<REdge>() {
        public REdge parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new REdge(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<REdge> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<REdge> getParserForType() {
        return PARSER;
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int NODES_FIELD_NUMBER = 1;
    private java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable> nodes_;
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    public java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .Models.Refactorable nodes = 1;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    public static final int EDGES_FIELD_NUMBER = 2;
    private java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge> edges_;
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge> getEdgesList() {
      return edges_;
    }
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    public java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder> 
        getEdgesOrBuilderList() {
      return edges_;
    }
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    public int getEdgesCount() {
      return edges_.size();
    }
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge getEdges(int index) {
      return edges_.get(index);
    }
    /**
     * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
     */
    public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder getEdgesOrBuilder(
        int index) {
      return edges_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getNodesCount(); i++) {
        if (!getNodes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getEdgesCount(); i++) {
        if (!getEdges(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
      for (int i = 0; i < edges_.size(); i++) {
        output.writeMessage(2, edges_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      for (int i = 0; i < edges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, edges_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable)) {
        return super.equals(obj);
      }
      com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable other = (com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable) obj;

      boolean result = true;
      result = result && getNodesList()
          .equals(other.getNodesList());
      result = result && getEdgesList()
          .equals(other.getEdgesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      if (getEdgesCount() > 0) {
        hash = (37 * hash) + EDGES_FIELD_NUMBER;
        hash = (53 * hash) + getEdgesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.TFGRefactorable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.TFGRefactorable)
        com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.class, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.Builder.class);
      }

      // Construct using com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
          getEdgesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        if (edgesBuilder_ == null) {
          edges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          edgesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.internal_static_Models_TFGRefactorable_descriptor;
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable getDefaultInstanceForType() {
        return com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.getDefaultInstance();
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable build() {
        com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable buildPartial() {
        com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable result = new com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable(this);
        int from_bitField0_ = bitField0_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        if (edgesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            edges_ = java.util.Collections.unmodifiableList(edges_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.edges_ = edges_;
        } else {
          result.edges_ = edgesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable) {
          return mergeFrom((com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable other) {
        if (other == com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        if (edgesBuilder_ == null) {
          if (!other.edges_.isEmpty()) {
            if (edges_.isEmpty()) {
              edges_ = other.edges_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEdgesIsMutable();
              edges_.addAll(other.edges_);
            }
            onChanged();
          }
        } else {
          if (!other.edges_.isEmpty()) {
            if (edgesBuilder_.isEmpty()) {
              edgesBuilder_.dispose();
              edgesBuilder_ = null;
              edges_ = other.edges_;
              bitField0_ = (bitField0_ & ~0x00000002);
              edgesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEdgesFieldBuilder() : null;
            } else {
              edgesBuilder_.addAllMessages(other.edges_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getNodesCount(); i++) {
          if (!getNodes(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getEdgesCount(); i++) {
          if (!getEdges(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = new java.util.ArrayList<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder setNodes(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder setNodes(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder addNodes(com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder addNodes(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder addNodes(
          com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder addNodes(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.Refactorable nodes = 1;</code>
       */
      public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.Refactorable.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.RefactorableOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }

      private java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge> edges_ =
        java.util.Collections.emptyList();
      private void ensureEdgesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          edges_ = new java.util.ArrayList<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge>(edges_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder> edgesBuilder_;

      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge> getEdgesList() {
        if (edgesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(edges_);
        } else {
          return edgesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public int getEdgesCount() {
        if (edgesBuilder_ == null) {
          return edges_.size();
        } else {
          return edgesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge getEdges(int index) {
        if (edgesBuilder_ == null) {
          return edges_.get(index);
        } else {
          return edgesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder setEdges(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.set(index, value);
          onChanged();
        } else {
          edgesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder setEdges(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.set(index, builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder addEdges(com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.add(value);
          onChanged();
        } else {
          edgesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder addEdges(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.add(index, value);
          onChanged();
        } else {
          edgesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder addEdges(
          com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.add(builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder addEdges(
          int index, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.add(index, builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder addAllEdges(
          java.lang.Iterable<? extends com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge> values) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, edges_);
          onChanged();
        } else {
          edgesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder clearEdges() {
        if (edgesBuilder_ == null) {
          edges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          edgesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public Builder removeEdges(int index) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.remove(index);
          onChanged();
        } else {
          edgesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder getEdgesBuilder(
          int index) {
        return getEdgesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder getEdgesOrBuilder(
          int index) {
        if (edgesBuilder_ == null) {
          return edges_.get(index);  } else {
          return edgesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public java.util.List<? extends com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder> 
           getEdgesOrBuilderList() {
        if (edgesBuilder_ != null) {
          return edgesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(edges_);
        }
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder addEdgesBuilder() {
        return getEdgesFieldBuilder().addBuilder(
            com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder addEdgesBuilder(
          int index) {
        return getEdgesFieldBuilder().addBuilder(
            index, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.TFGRefactorable.REdge edges = 2;</code>
       */
      public java.util.List<com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder> 
           getEdgesBuilderList() {
        return getEdgesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder> 
          getEdgesFieldBuilder() {
        if (edgesBuilder_ == null) {
          edgesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdge.Builder, com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable.REdgeOrBuilder>(
                  edges_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          edges_ = null;
        }
        return edgesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.TFGRefactorable)
    }

    // @@protoc_insertion_point(class_scope:Models.TFGRefactorable)
    private static final com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable();
    }

    public static com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TFGRefactorable>
        PARSER = new com.google.protobuf.AbstractParser<TFGRefactorable>() {
      public TFGRefactorable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TFGRefactorable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TFGRefactorable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TFGRefactorable> getParserForType() {
      return PARSER;
    }

    public com.google.errorprone.bugpatterns.T2R.common.Models.TFGRefactorableOuterClass.TFGRefactorable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_TFGRefactorable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_TFGRefactorable_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_TFGRefactorable_REdge_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_TFGRefactorable_REdge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025TFGRefactorable.proto\022\006Models\032\022Refacto" +
      "rable.proto\"\232\001\n\017TFGRefactorable\022#\n\005nodes" +
      "\030\001 \003(\0132\024.Models.Refactorable\022,\n\005edges\030\002 " +
      "\003(\0132\035.Models.TFGRefactorable.REdge\0324\n\005RE" +
      "dge\022\013\n\003fst\030\001 \002(\005\022\013\n\003snd\030\002 \002(\005\022\021\n\tedgeVal" +
      "ue\030\003 \001(\tB5\n3com.google.errorprone.bugpat" +
      "terns.T2R.common.Models"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Models_TFGRefactorable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_TFGRefactorable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_TFGRefactorable_descriptor,
        new java.lang.String[] { "Nodes", "Edges", });
    internal_static_Models_TFGRefactorable_REdge_descriptor =
      internal_static_Models_TFGRefactorable_descriptor.getNestedTypes().get(0);
    internal_static_Models_TFGRefactorable_REdge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_TFGRefactorable_REdge_descriptor,
        new java.lang.String[] { "Fst", "Snd", "EdgeValue", });
    com.google.errorprone.bugpatterns.T2R.common.Models.RefactorableOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
